baseURL = 'https://huffmanwrites.org'
languageCode = 'en-us'
title = 'PRH Site'
theme = 'PaperMod'

[params]
  author = 'Phil Huffman'
  description = 'Writings on Stoicism, philosophy, and life'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.homeInfoParams]
    Title = "PRH Site"
    Content = "Writings on Stoicism, philosophy, and the pursuit of a well-lived life"

  [[params.socialIcons]]
    name = 'website'
    url = 'https://huffmanwrites.org'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 30
